using System.Collections.Frozen;

namespace NeoIPC.Reporting;

/// <summary>
/// Per-report map of language tag → QMD filename, populated at startup
/// by <see cref="ReportingWarmupHostedService"/>. The Quarto generators
/// look up the QMD file to render via <see cref="ForReport"/> based on
/// the negotiated locale.
/// </summary>
/// <remarks>
/// Reports ship with one master <c>{Report}.qmd</c> (English) plus one
/// <c>{Report}.&lt;lang&gt;.qmd</c> per supported locale, generated by
/// the toolkit's po4a localization pipeline. The warmup service scans
/// each report directory for those files and registers what it finds;
/// the registry is then read-only.
/// </remarks>
public sealed class ReportLanguageRegistry
{
    static readonly FrozenDictionary<string, string> Empty =
        FrozenDictionary<string, string>.Empty;

    readonly Dictionary<string, FrozenDictionary<string, string>> _byReport = new();

    /// <summary>Registers the language→file map for one report. Called from the warmup service.</summary>
    internal void Set(string reportName, IDictionary<string, string> languageToFile)
    {
        // Case-insensitive so the file lookup agrees with LocaleResolver, which
        // matches supported languages OrdinalIgnoreCase: the registry keys come
        // verbatim from qmd filenames (not guaranteed lower-case) while the
        // resolved locale's language subtag always is. An Ordinal map here would
        // let the resolver return Resolved for a mixed-case key that the QMD
        // lookup in QuartoReportProducer then misses, crashing the render.
        _byReport[reportName] = languageToFile.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Returns the language→file map for <paramref name="reportName"/>,
    /// or an empty map when the report is unknown.
    /// </summary>
    public IReadOnlyDictionary<string, string> ForReport(string reportName) =>
        _byReport.TryGetValue(reportName, out var d) ? d : Empty;
}
