using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace NeoIPC.Reporting.Generators;

/// <summary>
/// The two-tier-model source generator at the heart of NeoIPC.Reporting's
/// API surface.
/// </summary>
/// <remarks>
/// For every report whose <c>.qmd-schema.json</c> snapshot is registered
/// as an <c>&lt;AdditionalFiles&gt;</c> entry on the project, the generator
/// emits three artifacts:
/// <list type="bullet">
///   <item><description>
///   <c>partial record &lt;Report&gt;RenderParameters</c> — typed
///   reflection of every entry in the schema snapshot. Names, types, and
///   defaults are pulled from the snapshot, which mirrors the upstream
///   QMD <c>params:</c> block verbatim. The <i>internal</i> contract.
///   </description></item>
///   <item><description>
///   <c>&lt;Report&gt;QuartoArgumentBuilder.Build(p)</c> — yields one
///   <c>"key:value"</c> pair per non-null param, with type-aware
///   formatting (Date in ISO 8601, character via single-quoted YAML
///   scalar with embedded-quote doubling, etc.).
///   </description></item>
///   <item><description>
///   The <c>partial record &lt;Report&gt;ApiParameters</c> companion:
///   the <c>MapTo()</c> method (assigns each <c>[RenderParameter]</c>
///   property to the corresponding RenderParameters property,
///   threading any <c>Converter.Convert(...)</c> in between) and the
///   <c>Schema</c> ImmutableArray (driving the
///   <c>/parameters</c> endpoints).
///   </description></item>
/// </list>
/// <para>
/// Diagnostics:
/// </para>
/// <list type="bullet">
///   <item><description><b>NRP001</b> — an
///   <c>&lt;Report&gt;ApiParameters</c> declaration with one or more
///   <c>[RenderParameter]</c> properties has no matching schema-derived
///   <c>&lt;Report&gt;RenderParameters</c>. Likely a missing
///   <c>&lt;AdditionalFiles&gt;</c> entry, or a stale snapshot.</description></item>
///   <item><description><b>NRP002</b> — a
///   <c>[RenderParameter("name")]</c> attribute references a param that
///   doesn't exist in the snapshot (typo or QMD-side rename).</description></item>
/// </list>
/// </remarks>
[Generator]
public sealed class ParameterRecordGenerator : IIncrementalGenerator
{
    static readonly DiagnosticDescriptor NoMatchingSchema = new(
        id: "NRP001",
        title: "No matching schema snapshot for ApiParameters",
        messageFormat: "No schema-derived RenderParameters record '{1}' found for '{0}'; ensure the corresponding .qmd-schema.json is in <AdditionalFiles> (regenerate the report-schema snapshots if one is missing)",
        category: "NeoIPC.Reporting.Generators",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    static readonly DiagnosticDescriptor UnknownSchemaParam = new(
        id: "NRP002",
        title: "RenderParameter references unknown param",
        messageFormat: "[RenderParameter(\"{0}\")] references a parameter that does not exist in {1}",
        category: "NeoIPC.Reporting.Generators",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var reportSchemas = context.AdditionalTextsProvider
            .Where(static f => f.Path.EndsWith(".qmd-schema.json", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, ct) => ReportSchemaParser.Parse(file, ct))
            .Where(static s => s is not null)
            .Select(static (s, _) => s!);

        context.RegisterSourceOutput(reportSchemas, EmitRenderParametersRecord);
        context.RegisterSourceOutput(reportSchemas, EmitQuartoArgumentBuilder);

        var apiSchemas = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is RecordDeclarationSyntax,
            static (ctx, ct) => ApiSchemaExtractor.TryExtract(ctx, ct))
            .Where(static s => s is not null)
            .Select(static (s, _) => s!);

        var paired = apiSchemas.Combine(reportSchemas.Collect());
        context.RegisterSourceOutput(paired, EmitApiPartial);
    }

    static void EmitRenderParametersRecord(SourceProductionContext spc, ReportSchema schema)
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated>\n");
        sb.Append("// Source: ").Append(schema.SourceFileName).Append('\n');
        sb.Append("// </auto-generated>\n");
        sb.Append("#nullable enable\n\n");
        sb.Append("namespace NeoIPC.Reporting;\n\n");
        sb.Append("public sealed partial record ").Append(schema.RecordName).Append('\n');
        sb.Append("{\n");

        for (int i = 0; i < schema.Parameters.Length; i++)
        {
            var p = schema.Parameters[i];
            if (i > 0) sb.Append('\n');
            EmitProperty(sb, p);
        }

        sb.Append("}\n");

        spc.AddSource($"{schema.RecordName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    static void EmitQuartoArgumentBuilder(SourceProductionContext spc, ReportSchema schema)
    {
        var className = schema.RecordName.EndsWith("RenderParameters")
            ? schema.RecordName.Substring(0, schema.RecordName.Length - "RenderParameters".Length) + "QuartoArgumentBuilder"
            : schema.RecordName + "QuartoArgumentBuilder";

        var sb = new StringBuilder();
        sb.Append("// <auto-generated>\n");
        sb.Append("// Source: ").Append(schema.SourceFileName).Append('\n');
        sb.Append("// </auto-generated>\n");
        sb.Append("#nullable enable\n\n");
        sb.Append("using System.Collections.Generic;\n");
        sb.Append("using System.Globalization;\n");
        sb.Append("using System.Linq;\n\n");
        sb.Append("namespace NeoIPC.Reporting;\n\n");
        sb.Append("public static class ").Append(className).Append('\n');
        sb.Append("{\n");
        sb.Append("    public static IEnumerable<string> Build(").Append(schema.RecordName).Append(" p)\n");
        sb.Append("    {\n");

        foreach (var param in schema.Parameters)
        {
            EmitArgumentLine(sb, param);
        }

        sb.Append("    }\n\n");
        sb.Append("    static string EscapeYamlScalar(string value)\n");
        sb.Append("    {\n");
        sb.Append("        if (string.IsNullOrEmpty(value)) return \"''\";\n");
        sb.Append("        return \"'\" + value.Replace(\"'\", \"''\") + \"'\";\n");
        sb.Append("    }\n");
        sb.Append("}\n");

        spc.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    static void EmitArgumentLine(StringBuilder sb, ReportParameter p)
    {
        var prop = "p." + p.PropertyName;
        var key = p.QmdName;

        switch (p.RType)
        {
            case "character":
                sb.Append("        if (").Append(prop).Append(" is not null)\n");
                sb.Append("            yield return \"").Append(key).Append(":\" + EscapeYamlScalar(").Append(prop).Append(");\n");
                break;
            case "character[]":
                sb.Append("        if (").Append(prop).Append(" is { Length: > 0 })\n");
                sb.Append("            yield return \"").Append(key).Append(":[\" + string.Join(\",\", ").Append(prop).Append(".Select(EscapeYamlScalar)) + \"]\";\n");
                break;
            case "logical":
                sb.Append("        if (").Append(prop).Append(".HasValue)\n");
                sb.Append("            yield return \"").Append(key).Append(":\" + (").Append(prop).Append(".Value ? \"true\" : \"false\");\n");
                break;
            case "integer":
            case "numeric":
                sb.Append("        if (").Append(prop).Append(".HasValue)\n");
                sb.Append("            yield return \"").Append(key).Append(":\" + ").Append(prop).Append(".Value.ToString(CultureInfo.InvariantCulture);\n");
                break;
            case "Date":
                sb.Append("        if (").Append(prop).Append(".HasValue)\n");
                sb.Append("            yield return \"").Append(key).Append(":\" + ").Append(prop).Append(".Value.ToString(\"o\", CultureInfo.InvariantCulture);\n");
                break;
            default:
                sb.Append("        if (").Append(prop).Append(" is not null)\n");
                sb.Append("            yield return \"").Append(key).Append(":\" + EscapeYamlScalar(").Append(prop).Append(".ToString());\n");
                break;
        }
    }

    static void EmitProperty(StringBuilder sb, ReportParameter p)
    {
        if (!string.IsNullOrEmpty(p.Description))
        {
            sb.Append("    /// <summary>\n");
            foreach (var line in p.Description.Split('\n'))
            {
                sb.Append("    /// ");
                AppendXmlEscaped(sb, line);
                sb.Append('\n');
            }
            sb.Append("    /// </summary>\n");
        }
        if (p.Range is not null)
            sb.Append("    /// <remarks>Range: ").Append(p.Range).Append("</remarks>\n");
        if (p.Values.Length > 0)
            sb.Append("    /// <remarks>Values: ").Append(string.Join(", ", p.Values)).Append("</remarks>\n");
        sb.Append("    public ").Append(p.CSharpType).Append(' ').Append(p.PropertyName).Append(" { get; init; }\n");
    }

    static void EmitApiPartial(
        SourceProductionContext spc,
        (ApiSchema Api, ImmutableArray<ReportSchema> Schemas) tuple)
    {
        var (api, schemas) = tuple;

        var renderRecordName = api.TypeName.EndsWith("ApiParameters")
            ? api.TypeName.Substring(0, api.TypeName.Length - "ApiParameters".Length) + "RenderParameters"
            : api.TypeName + "RenderParameters";

        var schema = schemas.FirstOrDefault(q => q.RecordName == renderRecordName);

        var hasRenderParameterProperties = api.Properties.Any(p => p.QmdName is not null);

        // Validate: every [RenderParameter] must reference an existing schema param.
        if (hasRenderParameterProperties)
        {
            if (schema is null)
            {
                foreach (var prop in api.Properties)
                {
                    if (prop.QmdName is null) continue;
                    spc.ReportDiagnostic(Diagnostic.Create(
                        NoMatchingSchema, prop.Location, api.TypeName, renderRecordName));
                }
                return;
            }

            var schemaNames = schema.Parameters.Select(p => p.QmdName).ToImmutableHashSet();
            foreach (var prop in api.Properties)
            {
                if (prop.QmdName is null) continue;
                if (!schemaNames.Contains(prop.QmdName))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        UnknownSchemaParam, prop.Location, prop.QmdName, schema.SourceFileName));
                }
            }
        }

        if (schema is null) return;

        var schemaByName = schema.Parameters.ToDictionary(p => p.QmdName);

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");
        sb.Append("#nullable enable\n\n");
        if (!string.IsNullOrEmpty(api.Namespace))
            sb.Append("namespace ").Append(api.Namespace).Append(";\n\n");
        sb.Append("partial record ").Append(api.TypeName).Append('\n');
        sb.Append("{\n");

        sb.Append("    public ").Append(renderRecordName).Append(" MapTo() => new()\n");
        sb.Append("    {\n");
        foreach (var prop in api.Properties)
        {
            if (prop.QmdName is null) continue;
            var renderProp = ToPascalCase(prop.QmdName);
            sb.Append("        ").Append(renderProp).Append(" = ");
            if (prop.ConverterFqn is null)
                sb.Append(prop.PropertyName);
            else
                sb.Append(prop.ConverterFqn).Append(".Convert(").Append(prop.PropertyName).Append(')');
            sb.Append(",\n");
        }
        sb.Append("    };\n\n");

        EmitSchema(sb, api, schemaByName);

        sb.Append("}\n");

        spc.AddSource($"{api.TypeName}.Generated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    static void EmitSchema(
        StringBuilder sb,
        ApiSchema api,
        Dictionary<string, ReportParameter> schemaByName)
    {
        sb.Append("    public static global::System.Collections.Immutable.ImmutableArray<global::NeoIPC.Reporting.ApiParameterSchema> Schema { get; } =\n");
        sb.Append("    [\n");
        for (int i = 0; i < api.Properties.Length; i++)
        {
            var prop = api.Properties[i];
            var apiName = ToCamelCase(prop.PropertyName);
            string type;
            string? defaultValue = null;
            string? range = null;
            string[]? values = null;
            string? description = null;

            if (prop.QmdName is not null && schemaByName.TryGetValue(prop.QmdName, out var schemaParam))
            {
                type = schemaParam.RType;
                defaultValue = schemaParam.DefaultValue;
                range = schemaParam.Range;
                values = schemaParam.Values.IsDefaultOrEmpty ? null : schemaParam.Values.ToArray();
                description = string.IsNullOrEmpty(schemaParam.Description) ? null : schemaParam.Description;
            }
            else
            {
                type = CSharpTypeToRType(prop.CSharpType);
                if (prop.IsEnum && !prop.EnumValues.IsDefaultOrEmpty)
                    values = prop.EnumValues.ToArray();
            }

            var (min, max) = ParseRange(range);

            sb.Append("        new(");
            AppendCSharpString(sb, apiName);
            sb.Append(", ");
            AppendCSharpString(sb, type);
            sb.Append(", ");
            AppendCSharpStringOrNull(sb, defaultValue);
            sb.Append(", ");
            AppendCSharpStringOrNull(sb, min);
            sb.Append(", ");
            AppendCSharpStringOrNull(sb, max);
            sb.Append(", ");
            AppendCSharpStringArrayOrNull(sb, values);
            sb.Append(", ");
            AppendCSharpStringOrNull(sb, description);
            sb.Append(")");
            sb.Append(i < api.Properties.Length - 1 ? ",\n" : "\n");
        }
        sb.Append("    ];\n");
    }

    static (string? Min, string? Max) ParseRange(string? range)
    {
        if (string.IsNullOrEmpty(range)) return (null, null);
        var idx = range!.IndexOf("..", StringComparison.Ordinal);
        if (idx < 0) return (null, null);
        var minPart = range.Substring(0, idx).Trim();
        var maxPart = idx + 2 < range.Length ? range.Substring(idx + 2).Trim() : "";
        return (
            minPart.Length == 0 ? null : minPart,
            maxPart.Length == 0 ? null : maxPart);
    }

    static string CSharpTypeToRType(string cs)
    {
        // Strip nullable suffix; detect array suffix; map element type.
        var trimmed = cs.TrimEnd('?');
        var isArray = trimmed.EndsWith("[]", System.StringComparison.Ordinal);
        if (isArray) trimmed = trimmed.Substring(0, trimmed.Length - 2).TrimEnd('?');

        var element = trimmed switch
        {
            "string" => "character",
            "int" or "long" or "short" or "ushort" or "uint" or "ulong" or "byte" or "sbyte" => "integer",
            "double" or "float" or "decimal" => "numeric",
            "bool" => "logical",
            "DateOnly" => "Date",
            "DateTime" or "DateTimeOffset" => "POSIXct",
            _ => "character",
        };
        return isArray ? element + "[]" : element;
    }

    static string ToCamelCase(string pascalCase)
    {
        if (string.IsNullOrEmpty(pascalCase)) return pascalCase;
        if (char.IsUpper(pascalCase[0]))
            return char.ToLowerInvariant(pascalCase[0]) + pascalCase.Substring(1);
        return pascalCase;
    }

    static void AppendCSharpString(StringBuilder sb, string value)
    {
        sb.Append('"');
        foreach (var c in value)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(c); break;
            }
        }
        sb.Append('"');
    }

    static void AppendCSharpStringOrNull(StringBuilder sb, string? value)
    {
        if (value is null) sb.Append("null");
        else AppendCSharpString(sb, value);
    }

    static void AppendCSharpStringArrayOrNull(StringBuilder sb, string[]? values)
    {
        if (values is null || values.Length == 0)
        {
            sb.Append("null");
            return;
        }
        sb.Append("[");
        for (int i = 0; i < values.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            AppendCSharpString(sb, values[i]);
        }
        sb.Append("]");
    }

    static string ToPascalCase(string camelCase)
    {
        if (string.IsNullOrEmpty(camelCase)) return camelCase;
        return char.ToUpperInvariant(camelCase[0]) + camelCase.Substring(1);
    }

    static void AppendXmlEscaped(StringBuilder sb, string text)
    {
        foreach (var c in text)
        {
            switch (c)
            {
                case '<': sb.Append("&lt;"); break;
                case '>': sb.Append("&gt;"); break;
                case '&': sb.Append("&amp;"); break;
                default: sb.Append(c); break;
            }
        }
    }
}
